<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Content\Administrator\Extension\ContentComponent;
use Joomla\Component\Content\Site\Helper\RouteHelper;

// Create shortcuts to some parameters.
$params  = $this->item->params;
$canEdit = $params->get('access-edit');
$user    = Factory::getUser();
$info    = $params->get('info_block_position', 0);
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
?>

<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<div class="com-content-article item-page <?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
	<?php if ($this->params->get('show_page_heading')) : ?>
		<div class="page-header">
			<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
		</div>
	<?php endif;
	if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
		echo $this->item->pagination;
	}
	?>

	<?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
		|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

	<?php if ($params->get('show_title')) : ?>
		<div class="page-header mb-5 main-grid-child">
			<<?php echo $htag; ?> itemprop="headline" class="container">
				<?php echo $this->escape($this->item->title); ?>
			</<?php echo $htag; ?>>
			<?php if ($this->item->state == ContentComponent::CONDITION_UNPUBLISHED) : ?>
				<span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
			<?php endif; ?>
			<?php if ($isNotPublishedYet) : ?>
				<span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
			<?php endif; ?>
			<?php if ($isExpired) : ?>
				<span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
			<?php endif; ?>
		</div>
	<?php endif; ?>

	<?php if ($canEdit) : ?>
		<?php echo LayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item)); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" 
	?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentBeforeDisplay" 
	?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if ((int) $params->get('urls_position', 0) === 0) : ?>
		<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
		<?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
		<?php
		if (!empty($this->item->pagination) && !$this->item->paginationposition && !$this->item->paginationrelative) :
			echo $this->item->pagination;
		endif;
		?>
		<?php if (isset($this->item->toc)) :
			echo $this->item->toc;
		endif; ?>
		<div itemprop="articleBody" class="com-content-article__body grid-child">
			<?php echo $this->item->text; ?>

			<div class="paso paso-uno hidden visible" id="paso-uno">
				<p>¡Bienvenido/a!</p>
				<h2>Vamos a ayudarte a obtener tu turno.</h2>
				<p>Recordá que el Hospital es un centro de atención pediátrica de alta complejidad que atiende a niñas, niños y adolescentes de 0 a 15 años.</p>
				<p class="text-center">
					<a href="#paso-dos"><button class="btn btn-primary next">SIGUIENTE</button></a>
				</p>
			</div>

			<div class="paso paso-dos" id="paso-dos">
				<h2>¿Qué turno necesitás?</h2>
				<p class="consulta-estudio">
					<input type="radio" id="consulta" name="paso-dos" class="btn btn-primary consulta"><label for="consulta">Turno para una consulta <span class="asterisco">*</span></label>
					<input type="radio" id="estudio" name="paso-dos" class="btn btn-primary estudio"><label for="estudio">Turno para laboratorio o imágenes</label>
				</p>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-uno"><button class="btn btn-primary reset">Atrás</button></a></p>
					<p class="text-center">
						<a class="siguiente hidden" href="#"><button class="btn btn-primary next">SIGUIENTE</button></a>
					</p>
				</div>
				<div class="p-5 bg-light rounded-3"><p>* Para los siguientes estudios seleccionar <strong>"Turno para una consulta"</strong></p>
				<ul>
					<li>Eco cardiograma Doppler Color (Eco-cardio)</li>
					<li>Electroencefalograma del sueño (EEG)</li>
					<li>Electrocardiograma (ECG)</li>
					<li>Ergometría</li>
					<li>Holter</li>
					<li>PEAT (potenciales evocados auditivos)</li>
				</ul>
				</div>
			</div>

			<div class="paso paso-tres" id="paso-tres">
				<h2>¿Ya sos paciente del Hospital?</h2>
				<p>
					<input type="radio" id="paciente-si" name="paso-tres" class="btn btn-primary paciente-si"><label for="paciente-si">Sí</label>
					<input type="radio" id="paciente-no" name="paso-tres" class="btn btn-primary paciente-no"><label for="paciente-no">No</label>
				</p>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-dos"><button class="btn btn-primary reset prev">Atrás</button></a></p>
					<p class="text-center">
						<a class="siguiente hidden" href="#"><button class="btn btn-primary next">SIGUIENTE</button></a>
					</p>
				</div>
			</div>

			<div class="paso paso-tres_estudio" id="paso-tres_estudio">
				<p>Enviar un mail donde se incluya una foto de la solicitud médica (bono) de ambos lados, con el estudio solicitado, firma y sello del médico, y datos de la o el paciente.</p>
				<p>Indicar en el mail la fecha del próximo turno.</p>
				<p>La respuesta demora 5 días hábiles desde el envío del mail.</p>
				<h2>LABORATORIO</h2>
				<p><a href="mailto:turnoslab@garrahan.gov.ar">turnoslab@garrahan.gov.ar</a></p>
				<h2>IMÁGENES</h2>
				<h3>Ecografía - tomografía - contrastados</h3>
				<p><a href="mailto:turnosimag@garrahan.gov.ar">turnosimag@garrahan.gov.ar</a></p>
				<h2>RESONANCIA</h2>
				<p><a href="mailto:turnosresonancia@garrahan.gov.ar">turnosresonancia@garrahan.gov.ar</a></p>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-dos"><button class="btn btn-primary reset prev">Atrás</button></a></p>
				</div>
			</div>

			<div class="paso paso-viniste" id="paso-viniste">
				<h2>¿Viniste al Hospital en los últimos cuatro años?</h2>
				<p>
					<input type="radio" id="viniste-si" name="paso-viniste" class="btn btn-primary viniste-si"><label for="viniste-si">Sí</label>
					<input type="radio" id="viniste-no" name="paso-viniste" class="btn btn-primary viniste-no"><label for="viniste-no">No</label>
				</p>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-tres"><button class="btn btn-primary reset prev">Atrás</button></a></p>
					<p class="text-center">
						<a class="siguiente hidden" href="#"><button class="btn btn-primary next">SIGUIENTE</button></a>
					</p>
				</div>
			</div>

			<div class="paso paso-viniste-si" id="paso-viniste-si">
				<h2>¿Qué tipo de consulta necesitás?</h2>
				<p>
					<input type="radio" id="seguimiento" name="paso-viniste-si" class="btn btn-primary seguimiento"><label for="seguimiento">Turno de seguimiento</label>
					<input type="radio" id="nueva" name="paso-viniste-si" class="btn btn-primary nueva"><label for="nueva">Turno para una nueva especialidad</label>
				</p>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-viniste"><button class="btn btn-primary reset prev">Atrás</button></a></p>
					<p class="text-center">
						<a class="siguiente hidden" href="#"><button class="btn btn-primary next">SIGUIENTE</button></a>
					</p>
				</div>
			</div>

			<div class="paso paciente-no-paso" id="paciente-no-paso">
				<p>Antes de continuar es muy importante, <strong>para agilizar todo el proceso</strong>, que cuentes con:</p>
				<ul>
					<li><strong>Derivación</strong> de la o el pediatra, del centro de salud u hospital en el que se atiende el paciente, con el motivo de consulta en un hospital de alta complejidad.</li>
					<li><strong>Resumen de Historia Clínica</strong> y <strong>estudios realizados</strong> hasta el momento</li>
				</ul>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-tres"><button class="btn btn-primary reset prev">Atrás</button></a></p>
					<p class="text-center">
						<a class="siguiente" href="https://turnos.garrahan.gov.ar/PrimeraConsulta"><button class="btn btn-primary next">Siguiente</button></a>
					</p>
				</div>
			</div>

			<div class="paso paso-seguimiento-nueva" id="seguimiento-nueva">
				<p>Antes de continuar es muy importante, <strong>para agilizar todo el proceso</strong>, que cuentes con:</p>
				<ul>
					<li><strong>Solicitud</strong> de la o el profesional que requiere la nueva consulta.</li>
				</ul>
				<div class="acciones">
					<p class="text-center"><a class="atras" href="#paso-viniste-si"><button class="btn btn-primary reset prev">Atrás</button></a></p>
					<p class="text-center"><a class="siguiente" href="https://turnos.garrahan.gov.ar/NuevaEspecialidad"><button class="btn btn-primary siguiente-nueva next">Siguiente</button></a></p>
				</div>
			</div>

		</div>

		<?php if ($info == 1 || $info == 2) : ?>
			<?php if ($useDefList) : ?>
				<?php echo LayoutHelper::render('joomla.content.info_block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
			<?php endif; ?>
			<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
				<?php $this->item->tagLayout = new FileLayout('joomla.content.tags'); ?>
				<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
			<?php endif; ?>
		<?php endif; ?>

		<?php
		if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
			echo $this->item->pagination;
		?>
		<?php endif; ?>
		<?php if ((int) $params->get('urls_position', 0) === 1) : ?>
			<?php echo $this->loadTemplate('links'); ?>
		<?php endif; ?>
		<?php // Optional teaser intro text for guests 
		?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
		<?php echo LayoutHelper::render('joomla.content.intro_image', $this->item); ?>
		<?php echo HTMLHelper::_('content.prepare', $this->item->introtext); ?>
		<?php // Optional link to let them register to see the whole article. 
		?>
		<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
			<?php $menu = Factory::getApplication()->getMenu(); ?>
			<?php $active = $menu->getActive(); ?>
			<?php $itemId = $active->id; ?>
			<?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
			<?php $link->setVar('return', base64_encode(RouteHelper::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
			<?php echo LayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
		<?php endif; ?>
	<?php endif; ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" 
	?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>

<script>
	jQuery(".paso").addClass("hidden");

	jQuery("a").click(function() {
		jQuery(".paso.hidden.visible").removeClass("visible");
		var target = jQuery(this).attr("href");
		jQuery(target).addClass("visible");
	})

	var inputID = jQuery(this).find("label").attr("for");
	jQuery('#' + inputID).click();
	jQuery("input").click(function() {
		jQuery("input").removeClass('checked').next().removeClass('checked');
		jQuery(this).addClass('checked').next().addClass('checked');

		let link = event.target.id;
		console.log(link);

		if (link == 'consulta') {
			jQuery("#paso-dos a.siguiente").attr("href", "#paso-tres");
			jQuery("#paso-dos a.siguiente").addClass("visible");
			jQuery("#paso-dos a.siguiente").removeClass("hidden");
		}

		if (link == 'estudio') {
			jQuery("#paso-dos a.siguiente").attr("href", "#paso-tres_estudio");
			jQuery("#paso-dos a.siguiente").addClass("visible");
			jQuery("#paso-dos a.siguiente").removeClass("hidden");
		}

		if (link == 'paciente-si') {
			jQuery("#paso-tres a.siguiente").attr("href", "#paso-viniste");
			jQuery("#paso-tres a.siguiente").addClass("visible");
			jQuery("#paso-tres a.siguiente").removeClass("hidden");
		}

		if (link == 'paciente-no') {
			jQuery("#paso-tres a.siguiente").attr("href", "#paciente-no-paso");
			jQuery("#paso-tres a.siguiente").addClass("visible");
			jQuery("#paso-tres a.siguiente").removeClass("hidden");
		}

		if (link == 'viniste-si') {
			jQuery("#paso-viniste a.siguiente").attr("href", "#paso-viniste-si");
			jQuery("#paso-viniste a.siguiente").addClass("visible");
			jQuery("#paso-viniste a.siguiente").removeClass("hidden");
		}

		if (link == 'viniste-no') {
			jQuery("#paso-viniste a.siguiente").attr("href", "#paciente-no-paso");
			jQuery("#paso-viniste a.siguiente").addClass("visible");
			jQuery("#paso-viniste a.siguiente").removeClass("hidden");
		}

		if (link == 'seguimiento') {
			jQuery("#paso-viniste-si a.siguiente").attr("href", "https://turnos.garrahan.gov.ar/Seguimiento");
			jQuery("#paso-viniste-si a.siguiente").addClass("visible");
			jQuery("#paso-viniste-si a.siguiente").removeClass("hidden");
		}

		if (link == 'nueva') {
			jQuery("#paso-viniste-si a.siguiente").attr("href", "#seguimiento-nueva");
			jQuery("#paso-viniste-si a.siguiente").addClass("visible");
			jQuery("#paso-viniste-si a.siguiente").removeClass("hidden");
		}

	});
</script>